name: run ci

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    #- name: Install Go
     # uses: actions/setup-go@v2
      #with:
       # go-version: 1.16.4

    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Fetch required Go modules
     # run:  go mod download

    #- name: Build
      #run:  go build -v ./...

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

    - name: Run functional tests
      run:  python manage.py test



    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tdt4242-g01-frontend" #Must be unique in Heroku
        heroku_email: "eskil.torland@gmail.com"